### PR TITLE
Update to version 0.22.2

### PR DESCRIPTION
**Pull request by choffee**

### CODE REVIEW

**Comment by tzarebczan** [comment]
@choffee thanks for the PR. Would you be interested in being a community maintainer for future updates? I was going to ask @iuyte also.

**Comment by julianrichen** [comment]
bot, build

**Comment by julianrichen** [comment]
https://flathub.org/builds/#/builders/2/builds/2758

**Comment by julianrichen** [comment]
I agree with @tzarebczan, @choffee and/or @iuyte should be added as maintainers if they so wish it. I don't have as much time to now :(

**Comment by iuyte** [comment]
I would be happy to be a maintainer

**Comment by choffee** [comment]
I would be happy to as well.

**Comment by nedrichards** [comment]
Invitations sent.

**Pull request merged**
