### PR TITLE
[UPDATE] 0.34.2

### PR DESCRIPTION
**Pull request by kcseb**
[UPDATE] 0.34.2

### CODE REVIEW

**Comment by chpio** [comment]
this pr is "deprecated", why not close it?

**Comment by kcseb** [comment]
The builds have passed on both files needed for updating this to 0.34.2, please merge when available. 

What do you mean this is deprecated? @chpio

**Comment by chpio** [comment]
heee... ohh ok, your that one change into two PRs. i thought the other one superseded this one, sorry.

**Comment by kcseb** [comment]
Yeah, it's two different files but for the same respective update. I accidentally made it into two PRs. 

They're both needed for this to be updated to app version 0.34.2.

**Pull request closed without merging**
