### PR TITLE
Update LBRY to 0.51.1 version

### PR DESCRIPTION
**Pull request by jkonecny12**
Update to a new version to get rid of the warning in the app because the version is outdated.

### CODE REVIEW

**Comment by temrix** [comment]
@kcseb Please merge this.

**Comment by kcseb** [comment]
Thank you. Have been away from most tech for a bit. Please provide me an LBC address to send you some appreciation.

**Comment by temrix** [comment]
It seems like your website is down and I cannot join your Discord server so I can write you my address.

**Comment by jkonecny12** [comment]
> Thank you. Have been away from most tech for a bit. Please provide me an LBC address to send you some appreciation.

Not necessary, but if you really want, here is my address `bKsFUTawhb7FAMeN474MmJEw5TFPzNLczT` .

**Pull request merged**
