### PR TITLE
Update to 0.36.0

### PR DESCRIPTION
**Pull request by Zlopez**
Signed-off-by: Michal Konecny <michal.konecny@packetseekers.eu>

### CODE REVIEW

**Comment by Zlopez** [comment]
bot, build

**Comment by Zlopez** [comment]
I tried the test build and it's working.

**Comment by kcseb** [comment]
@Zlopez - When you make a PR to update the application, please make sure to also update the [application data](https://github.com/flathub/io.lbry.lbry-app/blob/master/io.lbry.lbry-app.appdata.xml) that reflects the change log [here](https://github.com/lbryio/lbry-desktop/releases/).

Your PR was merged and is appreciated, but make sure in the future to update both files. :) 

Thank you!

**Comment by Zlopez** [comment]
@kcseb Thanks for info, I don't use this file in my flatpak so I didn't know about it.

**Pull request merged**
